openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - 'url:http://localhost:8050'
description: Generated server url
paths:
  /api/v1/choreos/all:
    get:
      tags:
        - state-controller
      operationId: getAll
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Choreo'
components:
  schemas:
    Choreo:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
